server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Halcytone Content Generator Logs
  - job_name: halcytone-content-generator
    static_configs:
      - targets:
          - localhost
        labels:
          job: halcytone-content-generator
          service: content-generator
          environment: dry-run
          __path__: /var/log/halcytone/content-generator.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            component: component
            trace_id: trace_id
      - labels:
          level:
          component:
          trace_id:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  # Mock CRM Service Logs
  - job_name: mock-crm-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: mock-crm-service
          service: crm-mock
          environment: dry-run
          __path__: /var/log/halcytone/crm-mock.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            request_id: request_id
      - labels:
          level:
          request_id:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  # Mock Platform Service Logs
  - job_name: mock-platform-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: mock-platform-service
          service: platform-mock
          environment: dry-run
          __path__: /var/log/halcytone/platform-mock.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            request_id: request_id
      - labels:
          level:
          request_id:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  # System Docker Logs
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output