global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@halcytone.local'
  smtp_auth_username: 'alerts@halcytone.local'
  smtp_auth_password: 'alert-password-dev'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        service: halcytone
      receiver: 'halcytone-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook'
        send_resolved: true
        http_config:
          bearer_token: 'webhook-token-dev-2025'

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook/critical'
        send_resolved: true
        title: 'CRITICAL: Halcytone Alert'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook/warning'
        send_resolved: true
        title: 'WARNING: Halcytone Alert'

  - name: 'halcytone-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook/halcytone'
        send_resolved: true
        title: 'Halcytone Service Alert'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']