global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'halcytone-production'
    environment: '${ENVIRONMENT:-production}'

# Rules configuration
rule_files:
  - "rules/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Toombos - Main Application
  - job_name: 'toombos-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Mock CRM Service
  - job_name: 'mock-crm-service'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # Mock Platform Service
  - job_name: 'mock-platform-service'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # FastAPI Application Health Checks
  - job_name: 'halcytone-health'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Mock Services Health Checks
  - job_name: 'mock-services-health'
    static_configs:
      - targets:
          - 'host.docker.internal:8001'
          - 'host.docker.internal:8002'
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s