apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      tlsSkipVerify: true
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
    secureJsonData: {}

  - name: Prometheus-Alertmanager
    type: prometheus
    access: proxy
    orgId: 1
    url: http://alertmanager:9093
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      tlsSkipVerify: true
      httpMethod: GET
      queryTimeout: 30s

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    database: "[halcytone-logs-]YYYY.MM.DD"
    jsonData:
      timeField: "@timestamp"
      esVersion: 80
      includeFrozen: false
      logMessageField: message
      logLevelField: level
      interval: Daily
      maxConcurrentShardRequests: 5

  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      tlsSkipVerify: true
    secureJsonData: {}